<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: SDL - Win32 (WCE ARMV4I) Release Fixpoint--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\ms\LOCALS~1\Temp\RSP915.tmp" with contents
[
/nologo /W3 /Oxt /Ob2 /I "../../include" /I "../../src" /I "../../src/video" /I "../../src/thread" /I "../../src/thread/generic" /I "../../src/audio" /I "../../src/cdrom" /I "../../src/timer" /I "../../src/joystick" /I "../../src/events" /I "../../src/video/wincommon" /D "ARM" /D "_ARM_" /D "ARMV4I" /D "NDEBUG" /D _WIN32_WCE=500 /D "WCE_PLATFORM_Mantas500B" /D UNDER_CE=500 /D "UNICODE" /D "_UNICODE" /D "SDL_EXPORTS" /Fo"..\..\..\..\..\Build\Intermediate\SDL\ARMV4IRelease\\" /QRarch4T /QRinterwork-return /MC /c 
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\SDL.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_active.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\SDL_audio.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\SDL_audiocvt.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\SDL_audiodev.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_blit.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_blit_0.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_blit_1.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_blit_A.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_blit_N.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_bmp.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\cpuinfo\SDL_cpuinfo.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_cursor.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\windib\SDL_dibaudio.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\windib\SDL_dibevents.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\windib\SDL_dibvideo.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\disk\SDL_diskaudio.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\dummy\SDL_dummyaudio.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\SDL_error.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_events.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_expose.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\SDL_fatal.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_gamma.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\gapi\SDL_gapivideo.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\stdlib\SDL_getenv.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\stdlib\SDL_iconv.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\joystick\SDL_joystick.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_keyboard.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\stdlib\SDL_malloc.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\SDL_mixer.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\SDL_mixer_MMX_VC.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_mouse.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\dummy\SDL_nullevents.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\dummy\SDL_nullmouse.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\dummy\SDL_nullvideo.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_pixels.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\stdlib\SDL_qsort.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_quit.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\events\SDL_resize.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_RLEaccel.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\file\SDL_rwops.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_stretch.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\stdlib\SDL_string.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_surface.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\cdrom\dummy\SDL_syscdrom.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\thread\generic\SDL_syscond.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\wincommon\SDL_sysevents.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\joystick\dummy\SDL_sysjoystick.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\loadso\win32\SDL_sysloadso.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\wincommon\SDL_sysmouse.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\thread\win32\SDL_sysmutex.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\thread\win32\SDL_syssem.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\thread\win32\SDL_systhread.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\timer\wince\SDL_systimer.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\wincommon\SDL_syswm.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\thread\SDL_thread.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\timer\SDL_timer.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_video.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\audio\SDL_wave.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\wincommon\SDL_wingl.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_yuv.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_yuv_mmx.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\video\SDL_yuv_sw.c"
"D:\smu_smu-arobs-laptop_mn7_Hera\Projects\HeraMultimedia\FFMPEG_LIB\SDL-1.2.12\src\thread\win32\win_ce_semaphore.c"
]
Creating command line "clarm.exe @C:\DOCUME~1\ms\LOCALS~1\Temp\RSP915.tmp" 
Creating temporary file "C:\DOCUME~1\ms\LOCALS~1\Temp\RSP916.tmp" with contents
[
commctrl.lib coredll.lib /nologo /base:"0x00100000" /stack:0x10000,0x1000 /entry:"_DllMainCRTStartup" /dll /incremental:no /pdb:"..\..\..\..\..\Build\Intermediate\SDL\ARMV4IRelease\SDL.pdb" /nodefaultlib:"libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib" /out:"..\..\..\..\..\Build\Bin\WinCE\ARMV4I\SDL.dll" /implib:"..\..\..\..\..\Build\Intermediate\SDL\ARMV4IRelease\SDL.lib" /subsystem:windowsce,5.00 /MACHINE:THUMB 
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_active.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_audio.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_audiocvt.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_audiodev.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_blit.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_blit_0.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_blit_1.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_blit_A.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_blit_N.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_bmp.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_cpuinfo.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_cursor.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_dibaudio.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_dibevents.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_dibvideo.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_diskaudio.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_dummyaudio.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_error.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_events.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_expose.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_fatal.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_gamma.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_gapivideo.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_getenv.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_iconv.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_joystick.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_keyboard.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_malloc.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_mixer.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_mixer_MMX_VC.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_mouse.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_nullevents.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_nullmouse.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_nullvideo.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_pixels.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_qsort.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_quit.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_resize.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_RLEaccel.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_rwops.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_stretch.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_string.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_surface.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_syscdrom.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_syscond.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_sysevents.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_sysjoystick.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_sysloadso.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_sysmouse.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_sysmutex.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_syssem.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_systhread.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_systimer.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_syswm.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_thread.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_timer.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_video.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_wave.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_wingl.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_yuv.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_yuv_mmx.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\SDL_yuv_sw.obj"
"\smu_smu-arobs-laptop_mn7_Hera\Projects\Build\Intermediate\SDL\ARMV4IRelease\win_ce_semaphore.obj"
]
Creating command line "link.exe @C:\DOCUME~1\ms\LOCALS~1\Temp\RSP916.tmp"
<h3>Output Window</h3>
Compiling...
SDL.c
SDL_active.c
SDL_audio.c
SDL_audiocvt.c
SDL_audiodev.c
SDL_blit.c
SDL_blit_0.c
SDL_blit_1.c
SDL_blit_A.c
SDL_blit_N.c
SDL_bmp.c
SDL_cpuinfo.c
SDL_cursor.c
SDL_dibaudio.c
SDL_dibevents.c
SDL_dibvideo.c
SDL_diskaudio.c
SDL_dummyaudio.c
SDL_error.c
SDL_events.c
Generating Code...
d:\smu_smu-arobs-laptop_mn7_hera\projects\heramultimedia\ffmpeg_lib\sdl-1.2.12\src\audio\sdl_audio.c(404) : warning C4716: 'SDL_SetVolume' : must return a value
Compiling...
SDL_expose.c
SDL_fatal.c
SDL_gamma.c
SDL_gapivideo.c
SDL_getenv.c
SDL_iconv.c
SDL_joystick.c
SDL_keyboard.c
SDL_malloc.c
SDL_mixer.c
SDL_mixer_MMX_VC.c
SDL_mouse.c
SDL_nullevents.c
SDL_nullmouse.c
SDL_nullvideo.c
SDL_pixels.c
SDL_qsort.c
SDL_quit.c
SDL_resize.c
SDL_RLEaccel.c
Generating Code...
Compiling...
SDL_rwops.c
SDL_stretch.c
SDL_string.c
SDL_surface.c
SDL_syscdrom.c
SDL_syscond.c
SDL_sysevents.c
SDL_sysjoystick.c
SDL_sysloadso.c
SDL_sysmouse.c
SDL_sysmutex.c
SDL_syssem.c
SDL_systhread.c
SDL_systimer.c
SDL_syswm.c
SDL_thread.c
SDL_timer.c
SDL_video.c
SDL_wave.c
SDL_wingl.c
Generating Code...
Compiling...
SDL_yuv.c
SDL_yuv_mmx.c
SDL_yuv_sw.c
win_ce_semaphore.c
Generating Code...
Linking...
   Creating library ..\..\..\..\..\Build\Intermediate\SDL\ARMV4IRelease\SDL.lib and object ..\..\..\..\..\Build\Intermediate\SDL\ARMV4IRelease\SDL.exp




<h3>Results</h3>
SDL.dll - 0 error(s), 1 warning(s)
</pre>
</body>
</html>
